
select * from customer_analysis limit 10;

-- 1. what is the total revenue generated by male amd female customers??P
select gender,sum(purchase_Amount)as total_amount from customer_analysis group by gender;

-- male spend 157890 while female total_sales 75191

-- 2.which customer used promo code but still purchased more than the average purchase amount??
SELECT 
    customer_id,
     purchase_amount
FROM customer_analysis
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) as average_amount from customer_analysis);


-- 3.what are the top 5 products with the highest average review rating ??
select item_purchased, round(avg(review_rating),2) as avg_rating from customer_analysis group by 1 order by 2 desc limit 5;

-- 4. compare the avg purchase amount between the standard and the express shipping
select shipping_type,round(avg(purchase_amount),2) as avg_purchase 
from customer_analysis
where shipping_type in ('Standard','Express')
group by 1;

-- 5. do subscribes customers spend more? compare avg spend and total reviews between subscribers and non subscribers??
select subscription_status,
count(customer_id) as total_customer ,round(avg(purchase_amount),2) as total_Spend, count(review_rating) as total_reviews from customer_analysis
group by 1
order by 2 desc;

-- 6. which 5 products have the highest percentage of purchases with discounts applied??

select item_purchased,round(sum(case when discount_applied='Yes' then 1 else 0 end  )*100.0 / count(*)  ,2) as purchased_pencentage
from customer_analysis
group by 1
order by purchased_pencentage desc
limit 5;


-- -- 7. Find the customer segment as New,Returning, and Loyal
with cte as (
select customer_id,previous_purchases,
(case 
when previous_purchases=1 then 'New' 
when previous_purchases between 2 and 10  then 'Returning' 
else 'Loyal' end ) as  customer_segment
from customer_analysis)

select customer_segment , count(*) as number_of_people
from cte
group by 1


-- 8.what are the top three most purchased products within each category??

WITH cte1 AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer_analysis
    GROUP BY category, item_purchased
),
cte2 AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS rnk
    FROM cte1
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM cte2
WHERE rnk <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases ) also likely to purchase??

select subscription_status, count(*) as customers 
from customer_analysis
where previous_purchases>5
group by 1
;
-- 10.what is the revenue contribution of eah age group
select age_group ,sum(purchase_amount) as total_revenue
from customer_analysis
group by 1
order by 2 desc;

-- 11. find the total_orders  generated by the location??

select location, count(customer_id) as total_orders
from customer_analysis
group by 1
order by 2 desc;


-- 12 average purchase amount by each category.

select category,round(avg(purchase_amount),2) as avg_purchase_amount
from customer_analysis
group by 1
order by 2 desc;

-- 13. finding the median for each category 
WITH ranked AS (
    SELECT
        category,
        purchase_amount,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_amount
        ) AS rn,
        COUNT(*) OVER (
            PARTITION BY category
        ) AS total_count
    FROM customer_analysis
)
SELECT
    category,
    AVG(purchase_amount) AS median_purchase_amount
FROM ranked
WHERE rn IN (
    FLOOR((total_count + 1) / 2),
    CEIL((total_count + 1) / 2)
)
GROUP BY category;

-- 13. what total sales by the season??
select season, count(customer_id) as total_sales
from customer_analysis	
group by 1
order by 2 desc;

#14. What is the revenue generated in each season??

select season, sum(purchase_amount) as total_price
from customer_analysis
group by 1
order by 2 desc;



